### ISSUE TITLE
NodeSchool - Tutoriais

### ISSUE THREAD

**Issue by MiguelGalrao** [isel-leic-pi/PI-1819v-LI51N#1]
Boa Tarde Eng. @lfalcao-isel,

Para além dos tutoriais que nos mencionou:
- javascripting;
- learnyounode.

Quais são os outros recomendados?

Obrigado.

**Comment by Ralms** [comment]
Tens o TPC 3
https://github.com/isel-leic-pi/PI-1819v-LI51N/wiki/TPC

**Comment by MiguelGalrao** [comment]
Só reparei agora... 
Obrigado!!

**Comment by lfalcao-isel** [comment]
Os dois!

-- Luís Falcão

**Comment by lfalcao-isel** [comment]
Esses dois e o functional JavaScript

-- Luís Falcão
